# start with: dc run --rm --name mm --service-ports magicmirror

# if you need another (forked) mm repo add it as new remote to your git repo in windows and checkout the branch needed

services:
  magicmirror:
    image: registry.gitlab.com/khassel/magicmirror:develop_debug_curr
    container_name: mm
    environment:
      - XDG_RUNTIME_DIR=/tmp # use for running electron tests
      # - XDG_RUNTIME_DIR # use for running electron app on host display
      - DISPLAY=:0
      - NPM_CONFIG_PREFIX=/opt/magic_mirror/node_modules/
      - WAYLAND_DISPLAY=wayland-0
      - WLR_BACKENDS=headless
      - WLR_LIBINPUT_NO_DEVICES=1
      - WLR_RENDERER=pixman
      # - LD_PRELOAD=/usr/local/lib/libfaketime.so.1
      # - FAKETIME=-1d
    ports:
      - "8080:8080"
    shm_size: "268435456"
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/bash
      - -c
      - |
        ln -sf /opt/magic_mirror/node_modules /home/node/magicmirror/
        cd /home/node/magicmirror
        if [[ ! -f config/config.js ]]; then
          cp config/config.js.sample config/config.js
          sed -i 's|address:.*|address: "0.0.0.0",|g;s|ipWhitelist:.*|ipWhitelist: [],|g' config/config.js
        fi
        if [[ ! -f config/custom.css ]]; then
          touch config/custom.css
        fi
        labwc &  # use for running electron tests
        bash
    healthcheck:
      disable: true
    working_dir: /home/node/magicmirror
    volumes:
      # mount local project dir
      - /repo/foreign/MagicMirror:/home/node/magicmirror
      # mount XDG_RUNTIME_DIR and X11 stuff, needed for electron and displaying mm on host screen
      # - $XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - $HOME/.Xauthority:/home/node/.Xauthority
      # mount module to test with config
      # - /repo/k13/MMM-Flights:/home/node/magicmirror/modules/MMM-Flights
      # - /repo/k13/MMM-Flights/debug/config.js:/home/node/magicmirror/config/config.js
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mm.loadbalancer.server.port=8080"
      - "traefik.http.routers.mm.service=mm"
      - "traefik.http.routers.mm.entrypoints=http"
      - "traefik.http.routers.mm.rule=Host(`localhost`) && PathPrefix(`/mm/`)"
      - "traefik.http.routers.mm.middlewares=mm-stripprefix"
      - "traefik.http.middlewares.mm-stripprefix.stripprefix.prefixes=/mm"

  # traefik:
  #   image: traefik:latest
  #   container_name: traefik
  #   restart: unless-stopped
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedByDefault=false"
  #     - "--entryPoints.http.address=:80"
  #     - "--global.sendAnonymousUsage=false"
  #     - "--log.level=INFO"
  #     - "--api=true"
  #     - "--api.dashboard=true"
  #     - "--api.insecure=true"
  #   ports:
  #     - "80:80"
  #     - "8888:8080" # traefik dashboard localhost:8888
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
