stages:
  - build
  - test

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - ".gitlab/*.yaml"

default:
  image: ${BUILDKIT_IMG}:rootless
  tags:
    - saas-linux-medium-amd64

variables:
  GIT_DEPTH: 1
  TZ: "Europe/Berlin"
  MAGICMIRROR_VERSION: "v2.34.0"
  NODE_VERSION_MASTER: "24"
  NODE_VERSION_DEVELOP: "25"
  DEBIAN_VERSION_MASTER: "13"
  DEBIAN_VERSION_DEVELOP: "13"
  ALPINE_VERSION: "3.22"
  GITREPO_NAME: "MagicMirrorOrg/MagicMirror"
  GITREPO_URL: "https://github.com/${GITREPO_NAME}.git"

.rule:
  rules:
    - if: $TASK == "runtime"

.rulenomaster:
  rules:
    - if: $TASK == "runtime" && $CI_COMMIT_BRANCH != "master"

.init:
  script:
    - |
      set -e
      # master or not
      if [[ "${CI_COMMIT_BRANCH}" == "master" ]]; then
        export BUILDER_TAG=${MAGICMIRROR_VERSION}
        [[ -z "${NODE_VERSION}" ]] && export NODE_VERSION=${NODE_VERSION_MASTER}
        [[ -z "${DEBIAN_VERSION}" ]] && export DEBIAN_VERSION=${DEBIAN_VERSION_MASTER}
      else
        export BUILDER_TAG=${CI_COMMIT_BRANCH}
        [[ -z "${NODE_VERSION}" ]] && export NODE_VERSION=${NODE_VERSION_DEVELOP}
        [[ -z "${DEBIAN_VERSION}" ]] && export DEBIAN_VERSION=${DEBIAN_VERSION_DEVELOP}
      fi
      export GIT_INFO="commit=${CI_COMMIT_SHORT_SHA} ref=${CI_COMMIT_REF_NAME} date=${CI_COMMIT_TIMESTAMP} author=${CI_COMMIT_AUTHOR} title=${CI_COMMIT_TITLE}"

pages:
  stage: build
  image: hugomods/hugo:latest
  script:
    - |
      cd hugo
      export HUGO_PARAMS_MAGICMIRROR="$MAGICMIRROR_VERSION"
      export HUGO_PARAMS_NODEMASTER="$NODE_VERSION_MASTER"
      export HUGO_PARAMS_NODEDEVELOP="$NODE_VERSION_DEVELOP"
      export HUGO_PARAMS_DEBIANMASTER="$DEBIAN_VERSION_MASTER"
      export HUGO_PARAMS_DEBIANDEVELOP="$DEBIAN_VERSION_DEVELOP"
      hugo build --minify --baseURL https://khassel.gitlab.io/magicmirror
  artifacts:
    paths:
      - hugo/public
  publish: hugo/public
  rules:
    - if: $TASK == "pages"
    - if: $CI_COMMIT_BRANCH == "master" && $TASK == "runtime"
  environment:
    name: "$CI_COMMIT_BRANCH/Documentation"
    url: https://khassel.gitlab.io/magicmirror/

sync_readme:
  stage: build
  script:
    - readme
  rules:
    - if: $TASK == "readme"
    - if: $CI_COMMIT_BRANCH == "master" && $TASK == "runtime"
      needs:
        - build_debian_slim
        - build_debian_fat
        - build_alpine
  environment:
    name: "$CI_COMMIT_BRANCH/Docker Readme"
    url: https://hub.docker.com/r/karsten13/magicmirror

start_dev_build:
  variables:
    DEV_BRANCH: "develop"
  image:
    name: ${DOCKER_USER}/magicmirror:${DEV_BRANCH}_alpine
    entrypoint: [""]
    docker:
      user: root
  script:
    - |
      cd $MM_DIR
      # get second last commit (because build_info.sh added one):
      current_sha="$(git rev-parse @~)"
      wget -q --output-document=repo.json https://api.github.com/repos/${GITREPO_NAME}/git/ref/heads/${DEV_BRANCH}
      remote_sha="$(cat repo.json | sed -rn 's|.*"sha": "([a-z,0-9]*).*|\1|p')"
      echo "current_sha: $current_sha"
      echo "remote_sha:  $remote_sha"
      if [[ "$current_sha" == "$remote_sha" ]]; then
        echo "up to date, nothing to do."
      else
        apk add curl
        echo "remote has new commits, starting ${DEV_BRANCH} pipeline."
        curl --request POST "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline?token=${CI_JOB_TOKEN}&ref=${DEV_BRANCH}&variables\[TASK\]=runtime"
      fi
  rules:
    - if: $CI_COMMIT_BRANCH == $DEV_BRANCH && $TASK == "checkupdates"
