StylesPath = .vale/styles

Vocab = own

IgnoredScopes = code, tt, title

MinAlertLevel = suggestion

Packages = Microsoft, write-good, proselint, Hugo

[*.{md}]
# ^ This section applies to only Markdown files.
#
# You can change (or add) file extensions here
# to apply these settings to other file types.
#
# For example, to apply these settings to both
# Markdown and reStructuredText:
#
# [*.{md,rst}]
BasedOnStyles = Vale, Microsoft, write-good, proselint

# disable rules:
; proselint.Annotations = NO

[.vale/*]
 ; ignore since they are derived files
BasedOnStyles =