services:
  fedora:
    image: karsten13/magicmirror:fedora
    volumes:
      - ../../mounts/config:/opt/magic_mirror/config:z
      - /tmp/.X11-unix:/tmp/.X11-unix:z
    privileged: true
    environment:
      DISPLAY: unix:0.0
